name: Hola Mundo Action

on: 
  push:
    branches:
      - main

jobs:  #conj de tareas, instrucciones
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Ejecutar script de Hola Mundo
        run: |
          echo "¡Hola Mundo!"

